environment: Development
port: 8001

payment_db:
  ssl: disable
  port: 5432
  user: zaffere
  host: localhost
  password: ""

server_config:
  read_timeout: 25
  write_timeout: 25
  allow_methods:
    - GET
    - POST
  allow_origins:
    - "http://localhost:8000"

stripe_service:
  key: sk_test_51J3JViF3ZrLzHIuoeso9urc2F8T2YSBDcs0Fv3vyHKOq9soeNQxvHP64w8jLZyggHXfJBflHLcFWN3mIRQ2gaOig00iqJFspSK
  domain: "http://localhost:3000"
  currency: SGD
  success_url: "?success=true" 
  cancel_url: "?canceled=true"
